# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/152/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/152/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victor/itmo/3year/spo/lab1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victor/itmo/3year/spo/lab1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/152/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/152/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/itmo/3year/spo/lab1/CMakeFiles /home/victor/itmo/3year/spo/lab1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/itmo/3year/spo/lab1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named labSPO1

# Build rule for target.
labSPO1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 labSPO1
.PHONY : labSPO1

# fast build rule for target.
labSPO1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/build
.PHONY : labSPO1/fast

sources/commands.o: sources/commands.c.o

.PHONY : sources/commands.o

# target to build an object file
sources/commands.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/commands.c.o
.PHONY : sources/commands.c.o

sources/commands.i: sources/commands.c.i

.PHONY : sources/commands.i

# target to preprocess a source file
sources/commands.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/commands.c.i
.PHONY : sources/commands.c.i

sources/commands.s: sources/commands.c.s

.PHONY : sources/commands.s

# target to generate assembly for a file
sources/commands.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/commands.c.s
.PHONY : sources/commands.c.s

sources/filesystem_utils.o: sources/filesystem_utils.c.o

.PHONY : sources/filesystem_utils.o

# target to build an object file
sources/filesystem_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/filesystem_utils.c.o
.PHONY : sources/filesystem_utils.c.o

sources/filesystem_utils.i: sources/filesystem_utils.c.i

.PHONY : sources/filesystem_utils.i

# target to preprocess a source file
sources/filesystem_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/filesystem_utils.c.i
.PHONY : sources/filesystem_utils.c.i

sources/filesystem_utils.s: sources/filesystem_utils.c.s

.PHONY : sources/filesystem_utils.s

# target to generate assembly for a file
sources/filesystem_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/filesystem_utils.c.s
.PHONY : sources/filesystem_utils.c.s

sources/main.o: sources/main.c.o

.PHONY : sources/main.o

# target to build an object file
sources/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/main.c.o
.PHONY : sources/main.c.o

sources/main.i: sources/main.c.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/main.c.i
.PHONY : sources/main.c.i

sources/main.s: sources/main.c.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/main.c.s
.PHONY : sources/main.c.s

sources/mode.o: sources/mode.c.o

.PHONY : sources/mode.o

# target to build an object file
sources/mode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/mode.c.o
.PHONY : sources/mode.c.o

sources/mode.i: sources/mode.c.i

.PHONY : sources/mode.i

# target to preprocess a source file
sources/mode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/mode.c.i
.PHONY : sources/mode.c.i

sources/mode.s: sources/mode.c.s

.PHONY : sources/mode.s

# target to generate assembly for a file
sources/mode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/mode.c.s
.PHONY : sources/mode.c.s

sources/operations_ext.o: sources/operations_ext.c.o

.PHONY : sources/operations_ext.o

# target to build an object file
sources/operations_ext.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/operations_ext.c.o
.PHONY : sources/operations_ext.c.o

sources/operations_ext.i: sources/operations_ext.c.i

.PHONY : sources/operations_ext.i

# target to preprocess a source file
sources/operations_ext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/operations_ext.c.i
.PHONY : sources/operations_ext.c.i

sources/operations_ext.s: sources/operations_ext.c.s

.PHONY : sources/operations_ext.s

# target to generate assembly for a file
sources/operations_ext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/operations_ext.c.s
.PHONY : sources/operations_ext.c.s

sources/output_util.o: sources/output_util.c.o

.PHONY : sources/output_util.o

# target to build an object file
sources/output_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/output_util.c.o
.PHONY : sources/output_util.c.o

sources/output_util.i: sources/output_util.c.i

.PHONY : sources/output_util.i

# target to preprocess a source file
sources/output_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/output_util.c.i
.PHONY : sources/output_util.c.i

sources/output_util.s: sources/output_util.c.s

.PHONY : sources/output_util.s

# target to generate assembly for a file
sources/output_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/output_util.c.s
.PHONY : sources/output_util.c.s

sources/partition.o: sources/partition.c.o

.PHONY : sources/partition.o

# target to build an object file
sources/partition.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/partition.c.o
.PHONY : sources/partition.c.o

sources/partition.i: sources/partition.c.i

.PHONY : sources/partition.i

# target to preprocess a source file
sources/partition.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/partition.c.i
.PHONY : sources/partition.c.i

sources/partition.s: sources/partition.c.s

.PHONY : sources/partition.s

# target to generate assembly for a file
sources/partition.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/partition.c.s
.PHONY : sources/partition.c.s

sources/user_interface.o: sources/user_interface.c.o

.PHONY : sources/user_interface.o

# target to build an object file
sources/user_interface.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/user_interface.c.o
.PHONY : sources/user_interface.c.o

sources/user_interface.i: sources/user_interface.c.i

.PHONY : sources/user_interface.i

# target to preprocess a source file
sources/user_interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/user_interface.c.i
.PHONY : sources/user_interface.c.i

sources/user_interface.s: sources/user_interface.c.s

.PHONY : sources/user_interface.s

# target to generate assembly for a file
sources/user_interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/user_interface.c.s
.PHONY : sources/user_interface.c.s

sources/utils.o: sources/utils.c.o

.PHONY : sources/utils.o

# target to build an object file
sources/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/utils.c.o
.PHONY : sources/utils.c.o

sources/utils.i: sources/utils.c.i

.PHONY : sources/utils.i

# target to preprocess a source file
sources/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/utils.c.i
.PHONY : sources/utils.c.i

sources/utils.s: sources/utils.c.s

.PHONY : sources/utils.s

# target to generate assembly for a file
sources/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labSPO1.dir/build.make CMakeFiles/labSPO1.dir/sources/utils.c.s
.PHONY : sources/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... labSPO1"
	@echo "... sources/commands.o"
	@echo "... sources/commands.i"
	@echo "... sources/commands.s"
	@echo "... sources/filesystem_utils.o"
	@echo "... sources/filesystem_utils.i"
	@echo "... sources/filesystem_utils.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/mode.o"
	@echo "... sources/mode.i"
	@echo "... sources/mode.s"
	@echo "... sources/operations_ext.o"
	@echo "... sources/operations_ext.i"
	@echo "... sources/operations_ext.s"
	@echo "... sources/output_util.o"
	@echo "... sources/output_util.i"
	@echo "... sources/output_util.s"
	@echo "... sources/partition.o"
	@echo "... sources/partition.i"
	@echo "... sources/partition.s"
	@echo "... sources/user_interface.o"
	@echo "... sources/user_interface.i"
	@echo "... sources/user_interface.s"
	@echo "... sources/utils.o"
	@echo "... sources/utils.i"
	@echo "... sources/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

